# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y cppcheck valgrind g++-multilib lib32stdc++6 libc6-dev libc6-dev-i386

script:
  # Test x64 CPU
  - cppcheck . --error-exitcode=1 --quiet
  - make
  - ./test
  - valgrind --error-exitcode=1 ./test 10000
  # Test x86 CPU (32-bit)
  - make CXXFLAGS="-m32 -g -O2 -Wall -pedantic -Wextra -Werror -Wno-unused-parameter -Wno-long-long"
  - ./test
  - valgrind --error-exitcode=1 ./test 10000
